package com.dyno.export;

import com.dyno.history.CompareRunsResponseDto;
import com.dyno.history.ComparedRunDto;
import com.dyno.history.RunHistoryDetailDto;
import com.dyno.history.RunHistoryFrameDto;
import com.dyno.presenter.ChartPlotPoint;
import com.dyno.presenter.ChartSeriesModel;
import com.dyno.presenter.CompareDisplayMapper;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.geom.Rectangle;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.canvas.PdfCanvas;
import com.itextpdf.kernel.pdf.xobject.PdfFormXObject;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.Border;
import com.itextpdf.layout.borders.SolidBorder;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Image;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.HorizontalAlignment;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;

import java.io.IOException;
import java.nio.file.Path;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Generates PDF summary reports for single runs and comparison views.
 *
 * <h3>Thai text rendering</h3>
 * All text is rendered using Sarabun-Regular.ttf embedded with IDENTITY_H encoding
 * via iText 7 Community. This covers the full Thai Unicode block (U+0E00–U+0E7F)
 * plus Latin, ensuring mixed Thai/English labels render correctly without substitution.
 *
 * <h3>Chart rendering</h3>
 * Charts are drawn directly onto a PdfFormXObject via iText 7's PdfCanvas API,
 * mapping power/torque vs RPM series data to PDF point coordinates. No JavaFX
 * or AWT dependency is required; the chart is fully deterministic from the run data.
 */
public final class DynoPdfExporter {

    // ---- Bilingual labels (English / Thai) -----------------------------------

    private static final String LBL_SINGLE_TITLE  = "DYNO RUN REPORT / รายงานผลการทดสอบไดโน";
    private static final String LBL_COMPARE_TITLE = "DYNO COMPARISON REPORT / รายงานผลการเปรียบเทียบ";
    private static final String LBL_RUN_SUMMARY   = "RUN SUMMARY / สรุปผลรัน";
    private static final String LBL_COMPARE_TABLE = "COMPARISON TABLE / ตารางเปรียบเทียบ";
    private static final String LBL_CHART         = "CHART / กราฟ";
    private static final String LBL_FOOTER        = "Generated by Dyno Operator Console";
    private static final String LBL_NO_DATA       = "No chart data / ไม่มีข้อมูลกราฟ";

    private static final String LBL_RUN_ID       = "Run ID / หมายเลขรัน";
    private static final String LBL_DATE         = "Date / วันที่";
    private static final String LBL_SOURCE_MODE  = "Source Mode / โหมดแหล่งข้อมูล";
    private static final String LBL_CORRECTION   = "Correction Mode / โหมดแก้ไข";
    private static final String LBL_PEAK_POWER   = "Peak Power / กำลังสูงสุด";
    private static final String LBL_PEAK_TORQUE  = "Peak Torque / แรงบิดสูงสุด";
    private static final String LBL_AMBIENT_TEMP = "Ambient Temp / อุณหภูมิ";
    private static final String LBL_HUMIDITY     = "Humidity / ความชื้น";
    private static final String LBL_PRESSURE     = "Pressure / ความดัน";
    private static final String LBL_CORR_FACTOR  = "Correction Factor / ตัวคูณแก้ไข";

    private static final String LBL_CMP_METRIC   = "Metric / ค่าที่วัด";
    private static final String LBL_CMP_POWER    = "Peak Power / กำลังสูงสุด (HP)";
    private static final String LBL_CMP_PWR_RPM  = "Peak Power RPM";
    private static final String LBL_CMP_TORQUE   = "Peak Torque / แรงบิดสูงสุด (Nm)";
    private static final String LBL_CMP_TQ_RPM   = "Peak Torque RPM";
    private static final String LBL_CMP_SPEED    = "Peak Speed / ความเร็วสูงสุด (km/h)";
    private static final String LBL_CMP_AFR      = "AFR at Peak / อัตราส่วนผสม";
    private static final String LBL_CMP_AMBIENT  = "Ambient at Peak / สภาพแวดล้อม";

    // ---- PDF colour palette ------------------------------------------------

    private static final DeviceRgb COL_ACCENT      = hexRgb("#1289CC");
    private static final DeviceRgb COL_TXT_MAIN    = hexRgb("#14161E");
    private static final DeviceRgb COL_TXT_MUTED   = hexRgb("#666A7A");
    private static final DeviceRgb COL_CELL_LABEL  = hexRgb("#EEF0F4");
    private static final DeviceRgb COL_CELL_VALUE  = hexRgb("#FFFFFF");
    private static final DeviceRgb COL_BORDER      = hexRgb("#CDD0D9");

    // ---- Chart series palette (matches compare view) -----------------------

    private static final String[] POWER_HEX  = {"#2EC4FF", "#7CFFCB", "#B4F36C", "#69B7FF"};
    private static final String[] TORQUE_HEX = {"#FFB547", "#F973B0", "#A78BFA", "#F59E0B"};

    // ---- Chart drawing constants -------------------------------------------

    private static final DeviceRgb CHART_BG     = hexRgb("#191A20");
    private static final DeviceRgb CHART_GRID   = hexRgb("#383840");
    private static final DeviceRgb CHART_BORDER = hexRgb("#585866");
    private static final DeviceRgb CHART_AXIS   = hexRgb("#A8AAB3");
    private static final float     CHART_ML     = 52f;   // left margin inside XObject
    private static final float     CHART_MB     = 36f;   // bottom margin
    private static final float     CHART_MR     = 14f;   // right margin
    private static final float     CHART_MT     = 14f;   // top margin

    private static final DecimalFormat FMT_1D   = new DecimalFormat("0.0");
    private static final DecimalFormat FMT_INT  = new DecimalFormat("#,##0");
    private static final DateTimeFormatter TS_FMT =
        DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private DynoPdfExporter() {
    }

    // =========================================================================
    // Public API
    // =========================================================================

    /**
     * Generates a single-run PDF report.
     *
     * @param detail     run metadata (peaks, config)
     * @param frames     full frame series (for ambient conditions and chart data)
     * @param outputFile destination .pdf path
     */
    public static void writeSingleRun(
        RunHistoryDetailDto detail,
        List<RunHistoryFrameDto> frames,
        Path outputFile
    ) throws IOException {
        PdfFont font = FontProvider.loadSarabunFont();
        PdfWriter writer = new PdfWriter(outputFile.toFile());
        PdfDocument pdfDoc = new PdfDocument(writer);
        Document doc = openDoc(pdfDoc, font);

        // Title
        addHeader(doc, LBL_SINGLE_TITLE, runLabel(detail), font);

        // Metadata + peaks
        doc.add(sectionTitle(LBL_RUN_SUMMARY, font));
        doc.add(buildMetadataTable(detail, font));
        doc.add(vSpacer(6));
        doc.add(buildPeakTable(detail, font));
        doc.add(vSpacer(6));

        // Ambient conditions from peak-power frame
        RunHistoryFrameDto peakFrame = findPeakFrame(frames, detail.getPeakPowerHp());
        if (peakFrame != null) {
            doc.add(buildAmbientTable(peakFrame, font));
            doc.add(vSpacer(6));
        }

        // Chart
        List<ChartSeriesModel> series = makeSingleRunSeries(detail.getRunId(), frames, 0);
        doc.add(sectionTitle(LBL_CHART, font));
        doc.add(makeChartImage(pdfDoc, series, contentWidth(), 255f, font));
        doc.add(vSpacer(12));

        // Footer
        addFooter(doc, font);
        doc.close();
    }

    /**
     * Generates a live-snapshot PDF from the current chart series (no stored run required).
     *
     * @param runLabel   display label for the report title
     * @param caption    optional subtitle (chart caption)
     * @param series     chart series from the live chart model
     * @param outputFile destination .pdf path
     */
    public static void writeLiveSnapshot(
        String runLabel,
        String caption,
        List<ChartSeriesModel> series,
        Path outputFile
    ) throws IOException {
        PdfFont font = FontProvider.loadSarabunFont();
        PdfWriter writer = new PdfWriter(outputFile.toFile());
        PdfDocument pdfDoc = new PdfDocument(writer);
        Document doc = openDoc(pdfDoc, font);

        String subtitle = (caption != null && !caption.trim().isEmpty())
            ? caption.trim()
            : "Live chart snapshot";
        addHeader(doc, LBL_SINGLE_TITLE,
            (runLabel != null && !runLabel.trim().isEmpty() ? runLabel.trim() : "LIVE") + " — " + subtitle,
            font);

        doc.add(sectionTitle(LBL_CHART, font));
        List<ChartSeriesModel> safeSeries = series != null ? series : Collections.<ChartSeriesModel>emptyList();
        doc.add(makeChartImage(pdfDoc, safeSeries, contentWidth(), 255f, font));
        doc.add(vSpacer(12));

        addFooter(doc, font);
        doc.close();
    }

    /**
     * Generates a comparison PDF report for 1–4 runs.
     *
     * @param response   compare response from backend (run detail + frames per run)
     * @param outputFile destination .pdf path
     */
    public static void writeCompare(
        CompareRunsResponseDto response,
        Path outputFile
    ) throws IOException {
        List<ComparedRunDto> runs = runsFrom(response);

        PdfFont font = FontProvider.loadSarabunFont();
        PdfWriter writer = new PdfWriter(outputFile.toFile());
        PdfDocument pdfDoc = new PdfDocument(writer);
        Document doc = openDoc(pdfDoc, font);

        // Title
        String subtitle = "Comparing " + runs.size() + " stored run" + (runs.size() == 1 ? "" : "s");
        addHeader(doc, LBL_COMPARE_TITLE, subtitle, font);

        // Comparison table
        doc.add(sectionTitle(LBL_COMPARE_TABLE, font));
        doc.add(buildCompareTable(runs, font));
        doc.add(vSpacer(12));

        // Chart with all run series overlaid
        List<ChartSeriesModel> allSeries = makeCompareSeries(runs);
        doc.add(sectionTitle(LBL_CHART, font));
        doc.add(makeChartImage(pdfDoc, allSeries, contentWidth(), 255f, font));
        doc.add(vSpacer(12));

        // Per-run metadata blocks
        for (int i = 0; i < runs.size(); i++) {
            ComparedRunDto cr = runs.get(i);
            if (cr.getRun() == null) {
                continue;
            }
            doc.add(sectionTitle(runLabel(cr.getRun()), font));
            doc.add(buildMetadataTable(cr.getRun(), font));
            doc.add(vSpacer(4));
            doc.add(buildPeakTable(cr.getRun(), font));
            doc.add(vSpacer(8));
        }

        addFooter(doc, font);
        doc.close();
    }

    // =========================================================================
    // Document setup helpers
    // =========================================================================

    private static Document openDoc(PdfDocument pdfDoc, PdfFont font) {
        Document doc = new Document(pdfDoc, PageSize.A4);
        doc.setMargins(48, 48, 48, 48);
        doc.setFont(font);
        doc.setFontSize(10);
        return doc;
    }

    /** A4 content width = 595 - 2*48 = 499 pt */
    private static float contentWidth() {
        return 499f;
    }

    // =========================================================================
    // Header / footer
    // =========================================================================

    private static void addHeader(
        Document doc,
        String title,
        String subtitle,
        PdfFont font
    ) {
        doc.add(new Paragraph(title)
            .setFont(font).setFontSize(17).setBold()
            .setFontColor(COL_TXT_MAIN)
            .setMarginBottom(4));

        if (subtitle != null && !subtitle.isEmpty()) {
            doc.add(new Paragraph(subtitle)
                .setFont(font).setFontSize(11)
                .setFontColor(COL_ACCENT)
                .setMarginBottom(2));
        }

        doc.add(new Paragraph(LBL_FOOTER + "  •  " + now())
            .setFont(font).setFontSize(8)
            .setFontColor(COL_TXT_MUTED)
            .setMarginBottom(10));

        // Accent divider
        doc.add(accentDivider(font));
    }

    private static void addFooter(Document doc, PdfFont font) {
        doc.add(new Table(UnitValue.createPercentArray(new float[]{1}))
            .setWidth(UnitValue.createPercentValue(100))
            .setBorder(Border.NO_BORDER)
            .setMarginTop(8)
            .addCell(new Cell()
                .setBorder(Border.NO_BORDER)
                .setBorderTop(new SolidBorder(COL_BORDER, 0.5f))
                .setPadding(4)
                .add(new Paragraph(LBL_FOOTER)
                    .setFont(font).setFontSize(8)
                    .setFontColor(COL_TXT_MUTED)
                    .setTextAlignment(TextAlignment.CENTER))));
    }

    private static Table accentDivider(PdfFont font) {
        return new Table(UnitValue.createPercentArray(new float[]{1}))
            .setWidth(UnitValue.createPercentValue(100))
            .setBorder(Border.NO_BORDER)
            .setMarginBottom(12)
            .addCell(new Cell()
                .setBorder(Border.NO_BORDER)
                .setBorderBottom(new SolidBorder(COL_ACCENT, 2f))
                .setPadding(0)
                .add(new Paragraph("").setFontSize(1)));
    }

    // =========================================================================
    // Table builders
    // =========================================================================

    private static Table buildMetadataTable(RunHistoryDetailDto d, PdfFont font) {
        Table t = twoCol();
        row(t, LBL_RUN_ID, runLabel(d), font);
        row(t, LBL_DATE, safe(d.getDate()), font);
        row(t, LBL_SOURCE_MODE, safe(d.getSourceMode()), font);
        row(t, LBL_CORRECTION, safe(d.getCorrectionMode()), font);
        return t;
    }

    private static Table buildPeakTable(RunHistoryDetailDto d, PdfFont font) {
        Table t = twoCol();
        row(t, LBL_PEAK_POWER,
            fmtN(d.getPeakPowerHp(), "HP") + "  @  " + fmtN(d.getPeakPowerRpm(), "RPM"), font);
        row(t, LBL_PEAK_TORQUE,
            fmtN(d.getPeakTorqueNm(), "Nm") + "  @  " + fmtN(d.getPeakTorqueRpm(), "RPM"), font);
        return t;
    }

    private static Table buildAmbientTable(RunHistoryFrameDto f, PdfFont font) {
        Table t = twoCol();
        row(t, LBL_AMBIENT_TEMP, fmtN(f.getAmbientTempC(), "°C"), font);
        row(t, LBL_HUMIDITY, fmtN(f.getHumidityPct(), "%"), font);
        row(t, LBL_PRESSURE, fmtN(f.getPressureHpa(), "hPa"), font);
        row(t, LBL_CORR_FACTOR, fmtFull(f.getCorrectionFactor()), font);
        return t;
    }

    private static Table buildCompareTable(List<ComparedRunDto> runs, PdfFont font) {
        int cols = runs.size() + 1;
        float[] widths = new float[cols];
        widths[0] = 2.2f;
        for (int i = 1; i < cols; i++) {
            widths[i] = 1.0f;
        }
        Table t = new Table(UnitValue.createPercentArray(widths))
            .setWidth(UnitValue.createPercentValue(100));

        // Header row
        hdrCell(t, LBL_CMP_METRIC, font);
        for (int i = 0; i < runs.size(); i++) {
            hdrCell(t, runLabel(runs.get(i).getRun()), font);
        }

        // Data rows (lambda-free, compatible with Java 8 source / Java 21 target)
        cmpRow(t, LBL_CMP_POWER, runs, font, new CmpFn() {
            public String get(ComparedRunDto r) {
                return r.getRun() == null ? "—" : fmtN(r.getRun().getPeakPowerHp(), "HP");
            }
        });
        cmpRow(t, LBL_CMP_PWR_RPM, runs, font, new CmpFn() {
            public String get(ComparedRunDto r) {
                return r.getRun() == null ? "—" : fmtN(r.getRun().getPeakPowerRpm(), "RPM");
            }
        });
        cmpRow(t, LBL_CMP_TORQUE, runs, font, new CmpFn() {
            public String get(ComparedRunDto r) {
                return r.getRun() == null ? "—" : fmtN(r.getRun().getPeakTorqueNm(), "Nm");
            }
        });
        cmpRow(t, LBL_CMP_TQ_RPM, runs, font, new CmpFn() {
            public String get(ComparedRunDto r) {
                return r.getRun() == null ? "—" : fmtN(r.getRun().getPeakTorqueRpm(), "RPM");
            }
        });
        cmpRow(t, LBL_CMP_SPEED, runs, font, new CmpFn() {
            public String get(ComparedRunDto r) {
                RunHistoryFrameDto pk = CompareDisplayMapper.peakPowerFrame(r);
                return fmtN(CompareDisplayMapper.frameValue(pk, CompareDisplayMapper.Metric.SPEED), "km/h");
            }
        });
        cmpRow(t, LBL_CMP_AFR, runs, font, new CmpFn() {
            public String get(ComparedRunDto r) {
                RunHistoryFrameDto pk = CompareDisplayMapper.peakPowerFrame(r);
                return fmtN(CompareDisplayMapper.frameValue(pk, CompareDisplayMapper.Metric.AFR), "");
            }
        });
        cmpRow(t, LBL_CMP_AMBIENT, runs, font, new CmpFn() {
            public String get(ComparedRunDto r) {
                return CompareDisplayMapper.ambientText(CompareDisplayMapper.peakPowerFrame(r));
            }
        });
        return t;
    }

    // =========================================================================
    // Chart: PdfFormXObject built from series data
    // =========================================================================

    private static Image makeChartImage(
        PdfDocument pdfDoc,
        List<ChartSeriesModel> series,
        float w,
        float h,
        PdfFont font
    ) {
        PdfFormXObject xObj = new PdfFormXObject(new Rectangle(0, 0, w, h));
        PdfCanvas cv = new PdfCanvas(xObj, pdfDoc);
        drawChart(cv, w, h, series, font);
        cv.release();
        Image img = new Image(xObj);
        img.setWidth(w);
        img.setHorizontalAlignment(HorizontalAlignment.LEFT);
        return img;
    }

    private static void drawChart(
        PdfCanvas cv,
        float totalW,
        float totalH,
        List<ChartSeriesModel> series,
        PdfFont font
    ) {
        // Plot area (inside the margins allocated for axis labels)
        float px = CHART_ML;
        float py = CHART_MB;
        float pw = totalW - CHART_ML - CHART_MR;
        float ph = totalH - CHART_MB - CHART_MT;

        // Compute data ranges across all series
        double maxX = 1000;
        double maxY = 100;
        boolean hasData = false;
        for (ChartSeriesModel s : series) {
            for (ChartPlotPoint p : s.getPoints()) {
                if (p.getX() > maxX) maxX = p.getX();
                if (p.getY() > maxY) maxY = p.getY();
                hasData = true;
            }
        }
        maxX = niceMax(maxX, 1000);
        maxY = niceMax(maxY, 50);

        // Plot background
        cv.saveState();
        cv.setFillColor(CHART_BG);
        cv.rectangle(px, py, pw, ph);
        cv.fill();
        cv.restoreState();

        // Grid lines
        cv.saveState();
        cv.setStrokeColor(CHART_GRID);
        cv.setLineWidth(0.4f);
        int xDiv = 8;
        int yDiv = 6;
        for (int i = 1; i < xDiv; i++) {
            float gx = px + pw * i / (float) xDiv;
            cv.moveTo(gx, py).lineTo(gx, py + ph).stroke();
        }
        for (int i = 1; i < yDiv; i++) {
            float gy = py + ph * i / (float) yDiv;
            cv.moveTo(px, gy).lineTo(px + pw, gy).stroke();
        }
        cv.restoreState();

        // Plot border
        cv.saveState();
        cv.setStrokeColor(CHART_BORDER);
        cv.setLineWidth(0.8f);
        cv.rectangle(px, py, pw, ph);
        cv.stroke();
        cv.restoreState();

        // Series lines
        for (ChartSeriesModel s : series) {
            List<ChartPlotPoint> pts = s.getPoints();
            if (pts.isEmpty()) continue;
            cv.saveState();
            cv.setStrokeColor(hexRgb(s.getColorHex()));
            cv.setLineWidth(1.6f);
            boolean first = true;
            for (int i = 0; i < pts.size(); i++) {
                ChartPlotPoint p = pts.get(i);
                float cx = clamp(px + (float) (p.getX() / maxX) * pw, px, px + pw);
                float cy = clamp(py + (float) (p.getY() / maxY) * ph, py, py + ph);
                if (first) { cv.moveTo(cx, cy); first = false; }
                else        { cv.lineTo(cx, cy); }
            }
            if (!first) cv.stroke();
            cv.restoreState();
        }

        // No-data label
        if (!hasData) {
            chartText(cv, font, 8f, LBL_NO_DATA, CHART_AXIS,
                px + pw / 2f - 50, py + ph / 2f - 4);
        }

        // X axis tick labels
        for (int i = 0; i <= xDiv; i++) {
            double dataX = maxX * i / (double) xDiv;
            float cx = px + pw * i / (float) xDiv;
            String lbl = FMT_INT.format(dataX);
            float tw = font.getWidth(lbl, 7f);
            chartText(cv, font, 7f, lbl, CHART_AXIS, cx - tw / 2, py - 13);
        }

        // Y axis tick labels
        for (int i = 0; i <= yDiv; i++) {
            double dataY = maxY * i / (double) yDiv;
            float cy = py + ph * i / (float) yDiv;
            String lbl = FMT_INT.format(dataY);
            float tw = font.getWidth(lbl, 7f);
            chartText(cv, font, 7f, lbl, CHART_AXIS, px - tw - 4, cy - 3);
        }

        // Axis title
        chartText(cv, font, 7f, "RPM", CHART_AXIS, px + pw / 2f - 7, py - 26);

        // Legend (top-left inside plot area)
        float legX = px + 6;
        float legY = py + ph - 8;
        for (int i = 0; i < series.size(); i++) {
            ChartSeriesModel s = series.get(i);
            cv.saveState();
            cv.setFillColor(hexRgb(s.getColorHex()));
            cv.rectangle(legX, legY - 5, 8, 6);
            cv.fill();
            cv.restoreState();
            chartText(cv, font, 7f, s.getLabel(), CHART_AXIS, legX + 11, legY - 5);
            legY -= 11;
        }
    }

    private static void chartText(
        PdfCanvas cv,
        PdfFont font,
        float size,
        String text,
        DeviceRgb color,
        float x,
        float y
    ) {
        cv.saveState();
        cv.setFillColor(color);
        cv.beginText()
            .setFontAndSize(font, size)
            .moveText(x, y)
            .showText(text)
            .endText();
        cv.restoreState();
    }

    // =========================================================================
    // Series builders from frame data
    // =========================================================================

    private static List<ChartSeriesModel> makeSingleRunSeries(
        Long runId,
        List<RunHistoryFrameDto> frames,
        int colorIndex
    ) {
        List<ChartPlotPoint> pwrPts = new ArrayList<ChartPlotPoint>();
        List<ChartPlotPoint> tqPts  = new ArrayList<ChartPlotPoint>();
        for (int i = 0; i < frames.size(); i++) {
            RunHistoryFrameDto f = frames.get(i);
            Double rpm = f.getEngineRpm();
            if (rpm == null || rpm.doubleValue() <= 0) continue;
            if (f.getPowerHp() != null && f.getPowerHp().doubleValue() >= 0) {
                pwrPts.add(new ChartPlotPoint(rpm.doubleValue(), f.getPowerHp().doubleValue()));
            }
            if (f.getTorqueNm() != null && f.getTorqueNm().doubleValue() >= 0) {
                tqPts.add(new ChartPlotPoint(rpm.doubleValue(), f.getTorqueNm().doubleValue()));
            }
        }
        int ci = colorIndex % POWER_HEX.length;
        String label = runId != null ? String.format("RUN-%05d", runId.longValue()) : "RUN";
        List<ChartSeriesModel> out = new ArrayList<ChartSeriesModel>(2);
        if (!pwrPts.isEmpty()) {
            out.add(new ChartSeriesModel("pw-" + runId, label + " Power",  POWER_HEX[ci],  pwrPts));
        }
        if (!tqPts.isEmpty()) {
            out.add(new ChartSeriesModel("tq-" + runId, label + " Torque", TORQUE_HEX[ci], tqPts));
        }
        return out;
    }

    private static List<ChartSeriesModel> makeCompareSeries(List<ComparedRunDto> runs) {
        List<ChartSeriesModel> all = new ArrayList<ChartSeriesModel>();
        for (int i = 0; i < runs.size(); i++) {
            ComparedRunDto cr = runs.get(i);
            if (cr.getRun() == null) continue;
            List<RunHistoryFrameDto> frames = cr.getFrames() != null
                ? cr.getFrames() : Collections.<RunHistoryFrameDto>emptyList();
            all.addAll(makeSingleRunSeries(cr.getRun().getRunId(), frames, i));
        }
        return all;
    }

    // =========================================================================
    // Table cell helpers
    // =========================================================================

    private static Table twoCol() {
        return new Table(UnitValue.createPercentArray(new float[]{1.6f, 2.4f}))
            .setWidth(UnitValue.createPercentValue(100));
    }

    private static void row(Table t, String label, String value, PdfFont font) {
        t.addCell(new Cell()
            .add(new Paragraph(label).setFont(font).setFontSize(9).setFontColor(COL_TXT_MAIN))
            .setBackgroundColor(COL_CELL_LABEL)
            .setBorder(new SolidBorder(COL_BORDER, 0.5f))
            .setPadding(5));
        t.addCell(new Cell()
            .add(new Paragraph(value).setFont(font).setFontSize(9).setFontColor(COL_TXT_MAIN))
            .setBackgroundColor(COL_CELL_VALUE)
            .setBorder(new SolidBorder(COL_BORDER, 0.5f))
            .setPadding(5));
    }

    private static void hdrCell(Table t, String text, PdfFont font) {
        t.addHeaderCell(new Cell()
            .add(new Paragraph(text).setFont(font).setFontSize(8).setBold()
                .setFontColor(COL_TXT_MAIN))
            .setBackgroundColor(COL_CELL_LABEL)
            .setBorder(new SolidBorder(COL_BORDER, 0.5f))
            .setPadding(4));
    }

    private static void cmpRow(
        Table t,
        String label,
        List<ComparedRunDto> runs,
        PdfFont font,
        CmpFn fn
    ) {
        t.addCell(new Cell()
            .add(new Paragraph(label).setFont(font).setFontSize(8).setBold()
                .setFontColor(COL_TXT_MAIN))
            .setBackgroundColor(COL_CELL_LABEL)
            .setBorder(new SolidBorder(COL_BORDER, 0.5f))
            .setPadding(4));
        for (int i = 0; i < runs.size(); i++) {
            t.addCell(new Cell()
                .add(new Paragraph(fn.get(runs.get(i))).setFont(font).setFontSize(8)
                    .setFontColor(COL_TXT_MAIN))
                .setBackgroundColor(COL_CELL_VALUE)
                .setBorder(new SolidBorder(COL_BORDER, 0.5f))
                .setPadding(4));
        }
    }

    private static Paragraph sectionTitle(String text, PdfFont font) {
        return new Paragraph(text)
            .setFont(font).setFontSize(10).setBold()
            .setFontColor(COL_TXT_MUTED)
            .setMarginTop(8).setMarginBottom(4);
    }

    private static Paragraph vSpacer(float height) {
        return new Paragraph("").setMarginTop(height).setMarginBottom(0).setFontSize(1);
    }

    // =========================================================================
    // Formatting / utility helpers
    // =========================================================================

    private static String fmtN(Double v, String unit) {
        if (v == null) return "—";
        String s = FMT_1D.format(v.doubleValue());
        return (unit == null || unit.isEmpty()) ? s : s + " " + unit;
    }

    private static String fmtFull(Double v) {
        return v == null ? "—" : String.valueOf(v.doubleValue());
    }

    private static String safe(String v) {
        return (v == null || v.trim().isEmpty()) ? "—" : v.trim();
    }

    private static String runLabel(RunHistoryDetailDto d) {
        if (d == null || d.getRunId() == null) return "RUN";
        return String.format("RUN-%05d", d.getRunId().longValue());
    }

    private static String now() {
        return LocalDateTime.now(ZoneId.systemDefault()).format(TS_FMT);
    }

    private static double niceMax(double raw, double step) {
        return Math.ceil(Math.max(raw, step) / step) * step;
    }

    private static float clamp(float v, float lo, float hi) {
        return Math.max(lo, Math.min(hi, v));
    }

    private static List<ComparedRunDto> runsFrom(CompareRunsResponseDto r) {
        if (r == null || r.getRuns() == null) {
            return Collections.<ComparedRunDto>emptyList();
        }
        return r.getRuns();
    }

    static DeviceRgb hexRgb(String hex) {
        if (hex == null || hex.length() < 7) {
            return new DeviceRgb(0.5f, 0.5f, 0.5f);
        }
        String h = hex.startsWith("#") ? hex.substring(1) : hex;
        int r = Integer.parseInt(h.substring(0, 2), 16);
        int g = Integer.parseInt(h.substring(2, 4), 16);
        int b = Integer.parseInt(h.substring(4, 6), 16);
        return new DeviceRgb(r / 255.0f, g / 255.0f, b / 255.0f);
    }

    private static RunHistoryFrameDto findPeakFrame(
        List<RunHistoryFrameDto> frames,
        Double peakPowerHp
    ) {
        if (frames == null || frames.isEmpty()) return null;
        RunHistoryFrameDto best = null;
        double bestP = Double.NEGATIVE_INFINITY;
        for (int i = 0; i < frames.size(); i++) {
            RunHistoryFrameDto f = frames.get(i);
            if (f.getPowerHp() == null) continue;
            double p = f.getPowerHp().doubleValue();
            if (peakPowerHp != null && Math.abs(p - peakPowerHp.doubleValue()) < 0.001) {
                return f;
            }
            if (p > bestP) { bestP = p; best = f; }
        }
        return best;
    }

    // =========================================================================
    // Inner interface
    // =========================================================================

    private interface CmpFn {
        String get(ComparedRunDto run);
    }
}
