[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_port = /dev/ttyUSB1
monitor_port = /dev/ttyUSB1

upload_speed = 921600
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=0