[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_port = /dev/ttyUSB1
monitor_port = /dev/ttyUSB1

upload_speed = 921600
monitor_speed = 115200

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=0